### ISSUE TITLE
isInWordle function

### ISSUE THREAD

**Issue by Bozrem** [Bozrem/wordle-word-calculator#1]
Simple starter issue that doesn't require digging into a large complicated project

Create a function or set of functions in the Main.java class that checks if the entered guess can be used in Wordle. The function should use the guessWords.txt file to search for the guess, and return a boolean value of if its in or not.

Pretty simple :)

Just comment if you would like to be assigned to try this out

**Comment by shrutikumar15** [comment]
Hi I would like to be assigned this task
